Alphabeta
tokyotechchess/minichess-AI-1 pull request #46
Opened 2022-10-27 03:26 UTC by Ryomatech

泣いちゃった❗️

2022-10-27 14:44 UTC, Ryomatech commented
bestPromotion という変数がプロモない時変更しないからプロモと関係ないdepthだと一回前の変更したPieceになるけど良いのですか。ダメだとプロモ以外のMoveでEMPTYSQを代入せねば

2022-10-27 15:35 UTC, Ryomatech commented
ステイルとチェックメイトは明日やるしん

2022-10-28 00:11 UTC, grkon03 requested changes

2022-10-28 00:11 UTC, grkon03 commented on src/header/board.cpp
> +                    for (int i = 0; i < &no_moves; i++)
&no_moves ではなく no_moves

ビルドエラー出てるよ(buildという項目を見ると、ビルドに成功するか失敗するか書いてあるので、そこを見ると良い)

2022-10-28 00:11 UTC, grkon03 commented on src/header/board.cpp
> +                    for (int i = 0; i < &no_moves; i++)
これね
<img width="888" alt="スクリーンショット 2022-10-28 9 11 49" src="https://user-images.githubusercontent.com/84032562/198420268-bd2445a4-edb3-45c8-a660-319a37797861.png">

2022-10-28 09:45 UTC, grkon03 commented
ごめん、LegalMovesのテストが終わってから見る

2022-10-28 15:37 UTC, grkon03 commented
今更ながら申し訳ないけど、AI関連はそっちのヘッダーに入れたい
なので、
minichessAI.h
minichessAI.cpp
みたいなものを作って、そこに書いてほしいですm(__)m

2022-10-28 16:13 UTC, grkon03 reviewed
見た感じ良さそう
(一応下のところの解釈があってるかだけ確認してから approve する)

2022-10-28 16:13 UTC, grkon03 commented on src/header/minichessAI.cpp
> +            }
この処理は、一回も MoveForce されなかったら場合とそうでない場合で分けてる感じで良いよね？

2022-10-28 16:15 UTC, Ryomatech commented
i--のせいでずれるやつ直しました

2022-10-28 16:16 UTC, Ryomatech commented on src/header/minichessAI.cpp
> +            }
最初のとこでb=copyにしてるので1回もiに入らなかったらそのままでターンは変わらないで1回でも入ると変わるという理解です

2022-10-28 16:18 UTC, grkon03 commented on src/header/minichessAI.cpp
> +            }
OK

2022-10-28 16:22 UTC, grkon03 requested changes

2022-10-28 16:22 UTC, grkon03 commented on src/header/minichessAI.h
> +        Piece bestMovesPromotion[MAX_BESTMOVES];
ここに Board now_analyzed みたいな変数を付け加えてもらえればOKかな

2022-10-28 16:22 UTC, Ryomatech commented on src/header/minichessAI.h
> +        Piece bestMovesPromotion[MAX_BESTMOVES];
なんだそれ

2022-10-28 16:23 UTC, Ryomatech commented on src/header/minichessAI.h
> +        Piece bestMovesPromotion[MAX_BESTMOVES];
たせばいいですか

2022-10-28 16:24 UTC, grkon03 commented on src/header/minichessAI.h
> +        Piece bestMovesPromotion[MAX_BESTMOVES];
うん

2022-10-28 16:26 UTC, grkon03 approved these changes
LGTM

2022-10-28 16:26 UTC, merged